#!/usr/bin/env python3
"""Analyze contribution balance from contributor Markdown reports."""

from __future__ import annotations

import argparse
import dataclasses
import datetime as dt
import os
import re
import statistics
from typing import List, Optional, Sequence


@dataclasses.dataclass
class RepositoryBalance:
    repository: str
    report_path: str
    is_fork: str
    contributor_count: int
    score_stddev: float
    mean_score: float


def parse_contributor_scores(markdown: str) -> List[float]:
    scores: List[float] = []
    in_table = False

    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("| Rank |") and "Weighted Score" in stripped:
            in_table = True
            continue

        if not in_table:
            continue

        if not stripped.startswith("|"):
            break

        if set(stripped.replace("|", "").replace(":", "").replace("-", "").strip()) == set():
            continue

        cells = [cell.strip() for cell in stripped.split("|")[1:-1]]
        if len(cells) < 10:
            continue

        try:
            scores.append(float(cells[-1]))
        except ValueError:
            continue

    return scores


def parse_repository_name(markdown: str, fallback: str) -> str:
    match = re.search(r"^# Contribution Report: (.+)$", markdown, flags=re.MULTILINE)
    return match.group(1).strip() if match else fallback


def parse_fork_flag(markdown: str) -> str:
    match = re.search(r"^- Fork: (Yes|No|Unknown)$", markdown, flags=re.MULTILINE)
    return match.group(1) if match else "Unknown"


def analyze_report_file(path: str) -> RepositoryBalance:
    with open(path, "r", encoding="utf-8") as handle:
        markdown = handle.read()

    scores = parse_contributor_scores(markdown)
    repo_name = parse_repository_name(markdown, fallback=os.path.basename(path))
    fork_flag = parse_fork_flag(markdown)

    if not scores:
        stddev = 0.0
        mean_score = 0.0
    elif len(scores) == 1:
        stddev = 0.0
        mean_score = scores[0]
    else:
        stddev = statistics.pstdev(scores)
        mean_score = statistics.mean(scores)

    return RepositoryBalance(
        repository=repo_name,
        report_path=path,
        is_fork=fork_flag,
        contributor_count=len(scores),
        score_stddev=stddev,
        mean_score=mean_score,
    )


def render_balance_report(rankings: Sequence[RepositoryBalance], chart_path: Optional[str] = None) -> str:
    lines = [
        "# Contribution Balance Analysis",
        "",
        f"- Generated At (UTC): {dt.datetime.now(dt.timezone.utc).isoformat()}",
        f"- Repositories analyzed: {len(rankings)}",
        "",
        "Lower standard deviation means more balanced contributions.",
        "",
        "| Rank | Repository | Fork | Contributors | Score Std Dev | Mean Score | Source Report |",
        "|---:|---|---|---:|---:|---:|---|",
    ]

    for rank, repo in enumerate(rankings, start=1):
        lines.append(
            f"| {rank} | {repo.repository} | {repo.is_fork} | {repo.contributor_count} | "
            f"{repo.score_stddev:.4f} | {repo.mean_score:.4f} | {repo.report_path} |"
        )

    if chart_path:
        lines.extend(["", f"![Balance Chart]({chart_path})"])

    lines.append("")
    return "\n".join(lines)


def maybe_create_chart(
    rankings: Sequence[RepositoryBalance], chart_output: Optional[str]
) -> Optional[str]:
    if not chart_output:
        return None

    try:
        import matplotlib.pyplot as plt  # type: ignore
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError(
            "matplotlib is required for --chart-output. Install it with: pip install matplotlib"
        ) from exc

    labels = [r.repository for r in rankings]
    values = [r.score_stddev for r in rankings]

    plt.figure(figsize=(max(8, len(labels) * 1.3), 5))
    plt.bar(labels, values)
    plt.ylabel("Standard Deviation (Weighted Score)")
    plt.title("Repository Contribution Balance")
    plt.xticks(rotation=30, ha="right")
    plt.tight_layout()
    plt.savefig(chart_output)
    plt.close()
    return chart_output


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "reports",
        nargs="+",
        help="One or more Markdown reports generated by contributor_measurement.py",
    )
    parser.add_argument("-o", "--output", default="balance_report.md", help="Markdown output path")
    parser.add_argument(
        "--chart-output",
        default=None,
        help="Optional image file path for chart output (requires matplotlib)",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()

    analyzed = [analyze_report_file(path) for path in args.reports]
    rankings = sorted(analyzed, key=lambda repo: (repo.score_stddev, repo.mean_score, repo.repository))

    chart_path = maybe_create_chart(rankings, args.chart_output)
    report = render_balance_report(rankings, chart_path=chart_path)

    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(report)

    print(f"Balance report written to: {args.output}")
    if chart_path:
        print(f"Chart written to: {chart_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
